### ISSUE TITLE
System.Web.Services.Protocols.SoapHttpClientProtocol Parameter Type issue

### ISSUE THREAD

**Issue by RamblingCookieMonster** [RamblingCookieMonster/SecretServer#1]
A number of functions include a parameter for WebServiceProxy, with type System.Web.Services.Protocols.SoapHttpClientProtocol.

This type is not loaded out of the gate.

Example symptom:
Get-Help Get-Secret
get-help : Unable to find type [System.Web.Services.Protocols.SoapHttpClientProtocol]. Make sure that the assembly that contains this type is loaded.

Workaround:
- Any session that has previously used New-WebServiceProxy will not run into this issue.
- Any scenario where New-SSConnection has been successfully run will not run into this issue (including at module load time, if SecretServer.xml includes a proxy property from previously running New-SSConnection)

**Comment by jgigler** [comment]
I'm not sure if this is the solution you're looking for, but in the module manifest SecretServer.psd1, if you specify System.Web.Services.dll in the Required Assemblies definition, I believe this solves your problem. I have no secret server to test with, but it resolves the Example Symptom you posted.

```
# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @('System.Web.Services.dll')
```

I submitted a pull request if you'd like to do more thorough testing.

**Comment by RamblingCookieMonster** [comment]
Nice, thank you for the heads up and help!  Tested and merged, works perfectly
