### ISSUE TITLE
someone broke your build script ;)

### ISSUE THREAD

**Issue by Plork** [RamblingCookieMonster/SecretServer#17]

**Comment by Jaykul** [comment]
I don't know how it got broken, but **I fixed it**, in case it was my fault ;-)
I don't see a way @RamblingCookieMonster, _for me_ to kick off the **re**builds on @Plork's pull requests...

**Comment by RamblingCookieMonster** [comment]
Hi!

I'll re-trigger them, but I suspect @Plork might need to rebase with the updated repo (i.e. retrigger will run old build code if I understand correctly).

Cheers!
